let countryMap = new Map();

countryMap.set(`Afghanistan`,`flags/af.svg`)
countryMap.set(`Albania`,`flags/al.svg`)
countryMap.set(`Algeria`,`flags/dz.svg`)
countryMap.set(`Andorra`,`flags/an.svg`)
countryMap.set(`Angola`,`flags/ag.svg`)
countryMap.set(`Antigua and Barbuda`,`flags/at.svg`)
countryMap.set(`Argentina`,`flags/ar.svg`)
countryMap.set(`Armenia`,`flags/ar.svg`)
countryMap.set(`Australia`,`flags/au.svg`)
countryMap.set(`Austria`,`flags/at.svg`)
countryMap.set(`Azerbaijan`,`flags/az.svg`)
countryMap.set(`Bahamas`,`flags/bs.svg`)
countryMap.set(`Bahrain`,`flags/bh.svg`)
countryMap.set(`Bangladesh`,`flags/bd.svg`)
countryMap.set(`Barbados`,`flags/bb
.svg`)
countryMap.set(`Belarus`,`flags/br.svg`)
countryMap.set(`Belgium`,`flags/be.svg`)
countryMap.set(`Belize`,`flags/bl.svg`)
countryMap.set(`Benin`,`flags/bn.svg`)
countryMap.set(`Bhutan`,`flags/bt.svg`)
countryMap.set(`Bolivia`,`flags/bo.svg`)
countryMap.set(`Botswana`,`flags/bw.svg`)
countryMap.set(`Brazil`,`flags/br.svg`)
countryMap.set(`Brunei`,`flags/bn.svg`)
countryMap.set(`Bulgaria`,`flags/bg.svg`)
countryMap.set(`Burkina Faso`,`flags/bf.svg`)
countryMap.set(`Burundi`,`flags/bi.svg`)
countryMap.set(`Cambodia`,`flags/kh.svg`)
countryMap.set(`Cameroon`,`flags/cm.svg`)
countryMap.set(`Canada`,`flags/ca.svg`)
countryMap.set(`Cape Verde`,`flags/cp.svg`)
countryMap.set(`Central African Republic`,`flags/cf.svg`)
countryMap.set(`Chad`,`flags/tc.svg`)
countryMap.set(`Chile`,`flags/cl.svg`)
countryMap.set(`China`,`flags/ch.svg`)
countryMap.set(`Colombia`,`flags/co.svg`)
countryMap.set(`Comoros`,`flags/cm.svg`)
countryMap.set(`Congo, Dem. Rep.`,`flags/cd.svg`)
countryMap.set(`Congo, Rep.`,`flags/cg.svg`)
countryMap.set(`Costa Rica`,`flags/cr.svg`)
countryMap.set(`Cote d'Ivoire`,`flags/cv.svg`)
countryMap.set(`Croatia`,`flags/cr.svg`)
countryMap.set(`Cuba`,`flags/cu.svg`)
countryMap.set(`Cyprus`,`flags/cy.svg`)
countryMap.set(`Czech Republic`,`flags/cz.svg`)
countryMap.set(`Denmark`,`flags/dn.svg`)
countryMap.set(`Djibouti`,`flags/dj.svg`)
countryMap.set(`Dominica`,`flags/do.svg`)
countryMap.set(`Dominican Republic`,`flags/dm.svg`)
countryMap.set(`Ecuador`,`flags/ec.svg`)
countryMap.set(`Egypt`,`flags/eg.svg`)
countryMap.set(`El Salvador`,`flags/sl.svg`)
countryMap.set(`Equatorial Guinea`,`flags/gn.svg`)
countryMap.set(`Eritrea`,`flags/er.svg`)
countryMap.set(`Estonia`,`flags/es.svg`)
countryMap.set(`Ethiopia`,`flags/et.svg`)
countryMap.set(`Fiji`,`flags/fj.svg`)
countryMap.set(`Finland`,`flags/fi.svg`)
countryMap.set(`France`,`flags/fr.svg`)
countryMap.set(`Gabon`,`flags/ga.svg`)
countryMap.set(`Gambia`,`flags/gm.svg`)
countryMap.set(`Georgia`,`flags/ge.svg`)
countryMap.set(`Germany`,`flags/de.svg`)
countryMap.set(`Ghana`,`flags/gh.svg`)
countryMap.set(`Greece`,`flags/gr.svg`)
countryMap.set(`Grenada`,`flags/gd.svg`)
countryMap.set(`Guatemala`,`flags/gt.svg`)
countryMap.set(`Guinea`,`flags/gi.svg`)
countryMap.set(`Guinea-Bissau`,`flags/gb.svg`)
countryMap.set(`Guyana`,`flags/gu.svg`)
countryMap.set(`Haiti`,`flags/ha.svg`)
countryMap.set(`Honduras`,`flags/hn.svg`)
countryMap.set(`Hungary`,`flags/hu.svg`)
countryMap.set(`Iceland`,`flags/is.svg`)
countryMap.set(`India`,`flags/in.svg`)
countryMap.set(`Indonesia`,`flags/id.svg`)
countryMap.set(`Iran`,`flags/iq.svg`)
countryMap.set(`Iraq`,`flags/ir.svg`)
countryMap.set(`Ireland`,`flags/ie.svg`)
countryMap.set(`Israel`,`flags/il.svg`)
countryMap.set(`Italy`,`flags/it.svg`)
countryMap.set(`Jamaica`,`flags/jm.svg`)
countryMap.set(`Japan`,`flags/jp.svg`)
countryMap.set(`Jordan`,`flags/jo.svg`)
countryMap.set(`Kazakhstan`,`flags/kz.svg`)
countryMap.set(`Kenya`,`flags/ke.svg`)
countryMap.set(`Kiribati`,`flags/ki.svg`)
countryMap.set(`North Korea`,`flags/kp.svg`)
countryMap.set(`South Korea`,`flags/kr.svg`)
countryMap.set(`Kuwait`,`flags/kw.svg`)
countryMap.set(`Kyrgyz Republic`,`flags/ky.svg`)
countryMap.set(`Lao`,`flags/la.svg`)
countryMap.set(`Latvia`,`flags/lv.svg`)
countryMap.set(`Lebanon`,`flags/lb.svg`)
countryMap.set(`Lesotho`,`flags/ls.svg`)
countryMap.set(`Liberia`,`flags/lr.svg`)
countryMap.set(`Libya`,`flags/ly.svg`)
countryMap.set(`Liechtenstein`,`flags/li.svg`)
countryMap.set(`Lithuania`,`flags/lt.svg`)
countryMap.set(`Luxembourg`,`flags/lu.svg`)
countryMap.set(`Macedonia, FYR`,`flags/mk.svg`)
countryMap.set(`Madagascar`,`flags/mg.svg`)
countryMap.set(`Malawi`,`flags/mw.svg`)
countryMap.set(`Malaysia`,`flags/my.svg`)
countryMap.set(`Maldives`,`flags/mv.svg`)
countryMap.set(`Mali`,`flags/ml.svg`)
countryMap.set(`Malta`,`flags/mt.svg`)
countryMap.set(`Mauritania`,`flags/mr.svg`)
countryMap.set(`Mauritius`,`flags/mu.svg`)
countryMap.set(`Mexico`,`flags/mx.svg`)
countryMap.set(`Moldova`,`flags/md.svg`)
countryMap.set(`Monaco`,`flags/mc.svg`)
countryMap.set(`Mongolia`,`flags/mg.svg`)
countryMap.set(`Montenegro`,`flags/mn.svg`)
countryMap.set(`Morocco`,`flags/ma.svg`)
countryMap.set(`Mozambique`,`flags/mo.svg`)
countryMap.set(`Myanmar`,`flags/mm.svg`)
countryMap.set(`Namibia`,`flags/na.svg`)
countryMap.set(`Nauru`,`flags/nr.svg`)
countryMap.set(`Nepal`,`flags/np.svg`)
countryMap.set(`Netherlands`,`flags/nl.svg`)
countryMap.set(`New Zealand`,`flags/nz.svg`)
countryMap.set(`Nicaragua`,`flags/ni.svg`)
countryMap.set(`Niger`,`flags/ne.svg`)
countryMap.set(`Nigeria`,`flags/ng.svg`)
countryMap.set(`Norway`,`flags/no.svg`)
countryMap.set(`Oman`,`flags/om.svg`)
countryMap.set(`Pakistan`,`flags/pk.svg`)
countryMap.set(`Palau`,`flags/pl.svg`)
countryMap.set(`Panama`,`flags/pa.svg`)
countryMap.set(`Papua New Guinea`,`flags/pn.svg`)
countryMap.set(`Paraguay`,`flags/pr.svg`)
countryMap.set(`Peru`,`flags/pe.svg`)
countryMap.set(`Philippines`,`flags/ph.svg`)
countryMap.set(`Poland`,`flags/pl.svg`)
countryMap.set(`Portugal`,`flags/pt.svg`)
countryMap.set(`Qatar`,`flags/qa.svg`)
countryMap.set(`Romania`,`flags/ro.svg`)
countryMap.set(`Russia`,`flags/ru.svg`)
countryMap.set(`Rwanda`,`flags/rw.svg`)
countryMap.set(`St. Lucia`,`flags/kn.svg`)
countryMap.set(`St. Vincent and the Grenadines`,`flags/lc.svg`)
countryMap.set(`Samoa`,`flags/ws.svg`)
countryMap.set(`San Marino`,`flags/sm.svg`)
countryMap.set(`Sao Tome and Principe`,`flags/st.svg`)
countryMap.set(`Saudi Arabia`,`flags/sa.svg`)
countryMap.set(`Senegal`,`flags/se.svg`)
countryMap.set(`Serbia`,`flags/sr.svg`)
countryMap.set(`Seychelles`,`flags/sy.svg`)
countryMap.set(`Sierra Leone`,`flags/sl.svg`)
countryMap.set(`Singapore`,`flags/sg.svg`)
countryMap.set(`Slovak Republic`,`flags/sv.svg`)
countryMap.set(`Slovenia`,`flags/sn.svg`)
countryMap.set(`Solomon Islands`,`flags/sl.svg`)
countryMap.set(`Somalia`,`flags/so.svg`)
countryMap.set(`South Africa`,`flags/za.svg`)
countryMap.set(`Spain`,`flags/es.svg`)
countryMap.set(`Sri Lanka`,`flags/lk.svg`)
countryMap.set(`Sudan`,`flags/sd.svg`)
countryMap.set(`Suriname`,`flags/su.svg`)
countryMap.set(`Sweden`,`flags/se.svg`)
countryMap.set(`Switzerland`,`flags/ch.svg`)
countryMap.set(`Syria`,`flags/sy.svg`)
countryMap.set(`Taiwan`,`flags/tw.svg`)
countryMap.set(`Tajikistan`,`flags/tj.svg`)
countryMap.set(`Tanzania`,`flags/tz.svg`)
countryMap.set(`Thailand`,`flags/th.svg`)
countryMap.set(`Timor-Leste`,`flags/tl.svg`)
countryMap.set(`Togo`,`flags/tg.svg`)
countryMap.set(`Tonga`,`flags/to.svg`)
countryMap.set(`Trinidad and Tobago`,`flags/tt.svg`)
countryMap.set(`Tunisia`,`flags/tn.svg`)
countryMap.set(`Turkey`,`flags/tr.svg`)
countryMap.set(`Turkmenistan`,`flags/tk.svg`)
countryMap.set(`Tuvalu`,`flags/tv.svg`)
countryMap.set(`Uganda`,`flags/ug.svg`)
countryMap.set(`Ukraine`,`flags/ua.svg`)
countryMap.set(`United Arab Emirates`,`flags/ae.svg`)
countryMap.set(`United Kingdom`,`flags/gb.svg`)
countryMap.set(`United States`,`flags/us.svg`)
countryMap.set(`Uruguay`,`flags/uy.svg`)
countryMap.set(`Uzbekistan`,`flags/uz.svg`)
countryMap.set(`Vanuatu`,`flags/vu.svg`)
countryMap.set(`Venezuela`,`flags/ve.svg`)
countryMap.set(`Palestine`,`flags/ps.svg`)
countryMap.set(`Vietnam`,`flags/vn.svg`)
countryMap.set(`Yemen`,`flags/ye.svg`)
countryMap.set(`Zambia`,`flags/zm.svg`)
countryMap.set(`Zimbabwe`,`flags/zw.svg`)
countryMap.set(`South Sudan`,`flags/ss.svg`)